appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: e7Eq2KDE/frrRftFLTXX0LUykIwuCSQ/lIC6OYSRjTFdRrvbOHigw5ECPFdR4fXbQMAQeTeF17Dkw1b9BYKXuMPPtCix0CIZ+nj0KVhGi+zxuNZUB8K4bUBFUXWQ3EWPNfeFhyfRrpe1xabJ1JpSzNXhAr/kpet+OnAezOUPnuY+kLl/rzvhatSi9AagflJw/tjOOa+z+rqbvnzE05Uoz3nDZgNDezjl1UUoiLDmHEq+DO+dcBpsDVF1gF689jygdLUzZiTYaYaADf861lCy9SPpKn2AltgL1RoOKvmSEhoy5eJ5HU8WmTXQFaUCuEN6ZjjVZXIkcBjnxw02E+9NBCPn/e+73AVNMmbY+z5zGzSqQkfcoVpMLmwFyUxArewllTV/q7V1j/wlavENO/099BJFibP8jEvIDkxbHImbGUAO0K2StKVJnSWCjm50RdhVLkXhNweSB8aeYIjDqlHhMEMWYYV87d5LvgFyLeEwpIItO055dqjiXksjpN5vQq4zLwUB7iEZ43cM6OohW52QDYHz6GqhhbQELiS3gZ1UTyisQJNLG1WMImjxFmhxcxqnW2scoLczDqHPA1njGqTytciKno5Ips5FS1XjM4qi9pHvuK/Feve+5LBfWME6THbbKGp92OuT30C3ndH6574N7epHcqLzt+4YIjrTTcZinKI=
conda_forge_output_validation: true
