travis:
  secure:
    BINSTAR_TOKEN: ox5Ixm/jgf2H1PwqjkpWYGAsYB7lIs2wKHFgQmN7XE7FJHYsJTwIPeDZ9SQUsbYSDv/9oZwCzbALT5F99jGcfyrZGxiOKPUk6nAgy9PbcmSG2xMzubHVY1cz3pYKyeuO5DxgMOAoD9W2vaXXGZ/EYFz2qA+5kohZOBl/hWIZfWBpsBptVPxg5NWUHzEgJYsgFs7fIdGLABnl3b0HEnskYsv5G8JGS2K3peUrR/3/JRb1UB85cDla7SbTtjq4F7Xje+f7U4UIFGllz+3hgaUT110G55Jjuf9bqARgF66Sp9MQEfMm2ZxSDEYUwh4d9ca6nRFhHU/foEEXZAJpo2lrhGq+FACnitOj+cBlSzC3pPKj+eAzrbAHrdZbFKXuztwEW2IQRa8cuw/fC9jOuF9hPSQg7RYoqWmcATcWAk/pr+eRVrglhISQwTuIInM61Lk8dsFBQuPneiDQQqePY0bVEEon5vz6FnxDxzR6sj9fUjbn/dIbMvrAzot3WbC9z6ohEOs/7klSxkTaXW1OJJg1T/pY952BhP9gEcJoxGxNxH7rwjyeBYUAwEo2Qgrfqf7xmyJE8VvbVdlZScfiNZjzJuRetkx+1yfZz4fmH69z39GvBBFKeQ5wpQ8fKxUa83N/Gj2Lut+IGX5UevMzbhAC5Yb+B+cGJcQYgy+DdieQwxE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
