travis:
  secure:
    BINSTAR_TOKEN: KdpFEE1TGF9nTCUga0Z4gw4cJkicT38U9HY3b1qIxmTDkmNgk5QfHTujHzLfVrNsjQmi6NJrO90PeJJD7mvxnh8VvHWqUOgYVKIo0plABJnNCbTdIJTdAb/eLN6sbf+vj4xP9mABYhhCWXFyb6YwUWjsRuKPR1rrZybl81COyMGGuIhqP+4an3/JluqB1VFr21fc4yhubZYe3zeShAoo7fy+JM6WD+Pq2zwkPVTknCRayNetiaUugl9v5cxe2cC+phhcFCCBrymXPsyRPAqur2h4UWaRDlREvzCqJOvkrfr+bAw2CCwB7bXLcDlnURg1qbm17jHq3eUUZhPWZWf2TO3ZFJUAS7gvqYp2VNVmIlpC/ugFd7XY7vkh/P3m+TSA1V5Tp+jiTFCtOUPbUVsrf4nQJDwg1353UQtXXBCJxNKWj1ju+JWDV6jKl8nZFW2t4t5O9BOsSYOMJg2D/DYmeidY5M6O7qE/QdiKHXHfSu9H3ip3I/m9Pjex3sB2ybZHbdChmIu63Y+fWn46/3LDwWXjSvOFdVCtiUyHLJNsScwZU1cKiTDwFwjGjxJGxZBJnGSMWuG7mg8c/WsSJqOM2i6RNpMxG/jnfio1rPZAIj/ToxwWIJw4zMZtGakiAs0J4QyTDuvdVrjAdCjuBlGPPzlRXa84FREBIgy6o2KNVyo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
